version: '3.3'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'banking'
      MYSQL_USER: 'rooti'
      MYSQL_PASSWORD: 'changeMe'
      MYSQL_ROOT_PASSWORD: 'changeMe'
    ports:
      - 3306:3306
    expose:
      - 3306
    volumes:
      - db_data:/var/lib/mysql
# Names our volume
volumes:
  db_data: